language: generic
if: type = cron OR type = api
script: ".travis/publish_report.sh"
# notifications:
#   email:
#     - commiter:
#       on_success: change
#       on_failure: always
#     - cron:
#       if: type = cron
#       recipients:
#         - support-dataclay@bsc.es
#       on_success: change
#       on_failure: always
