version: 2.7.dev.build{build}
build_cloud: bsccsdomci01
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
max_jobs: 1
build_script: ./report.sh
notifications:
  - provider: Email
    to:
      - support-dataclay@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true