version: 2.6.dev.build{build}
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
environment:
  GITHUB_SALT:
    secure: Kr7t+Nc/72GutMsnUJhJ8oF5tP9e6u7vABDy2IH+wKGNmi4rWSsDk5OaueM6tM2NBf97qMTvlgkxUxePS+m5FQ==
  GITHUB_SECRET:
    secure: cRcuNr+fBaRnMPeevkhasZnIVF1uIal3WT+5QCou/NQ=
  MN_SALT:
    secure: A2CVXopXaMJuIZw+vkdiklA4nLKgFmjW9W3PpofFBi1elXHhnPaoHbdOv6Rk1NHP04O7y8D7l21XzmPgYtZF8g==
  MN_SECRET:
    secure: fOYbgYSg0A2yudFL4mi8glRpB/VlAdbf0Genq44vLws=
build_script:
  - |
    docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e MN_SALT=$MN_SALT \
      -e MN_SECRET=$MN_SECRET \
      -e GITHUB_SALT=$GITHUB_SALT \
      -e GITHUB_SECRET=$GITHUB_SECRET \
      -w=$APPVEYOR_BUILD_FOLDER \
      bscdataclay/continuous-integration:reporting
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true