version: 2.6.dev.build{build}
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
environment:
  MN_SECRET:
    secure: fOYbgYSg0A2yudFL4mi8glRpB/VlAdbf0Genq44vLws=
  MN_SALT:
    secure: 36ZGkh6PxmQeiJfk3ErfZlpGGNXYLROluqkTmcByCrdRzAU3UjcSHJhsho5kLBOYHza4nGSLhRsZcSbu1EC5vA==
  GITHUB_SALT:
    secure: E689nv/EIj3BcQggYUTSGE4PYl+RbRnQvp31ISaoX56r/9nQYf6p+U7Gwq2v7Rs7T8ZIr0uWtHFkF9lfYrX/7Q==
  GITHUB_SECRET:
    secure: C4Y8YzQ0ALwDnNL/bObwyawrUODVVSlhIE4pnJ9kyw8=
build_script:
  - |
    docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e MN_SALT=$MN_SALT \
      -e MN_SECRET=$MN_SECRET \
      -w=$APPVEYOR_BUILD_FOLDER \
      bscdataclay/continuous-integration:reporting