version: 2.6.dev.build{build}
branches:
  only:
    - develop
skip_tags: true
skip_branch_with_pr: true
image: Ubuntu1804
environment:
  MN_SALT:
    secure: y0lD3CmSDZQx7zsNkyqUQyFtiV2eoewZ94bxSk9yoUrc6Mfgto18k7hzAitfVxs124Pai3GGvBpDZppuXikFPQ==
  MN_SECRET:
    secure: +ZRoLZnCowoJI/RvYao/XzgDz4usFDcZRX5aRoTBHUY=
  GITHUB_SALT:
    secure: 8se2vBODFmwfFwCpYkYJxB3xIq8LyUgmk1z08zNcoktOdOCtZfjqc9pya8K3jSOPQPSQ6fUvH4JHQ4A8PEojiA==
  GITHUB_SECRET:
    secure: Pa79AtdPwqqm5BmB4j6PHNy60bV7yur9hasBXfHSFrM=
build_script:
  - |
    docker run -v $APPVEYOR_BUILD_FOLDER:$APPVEYOR_BUILD_FOLDER \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e MN_SALT=$MN_SALT \
      -e MN_SECRET=$MN_SECRET \
      -e GITHUB_SALT=$GITHUB_SALT \
      -e GITHUB_SECRET=$GITHUB_SECRET \
      -w=$APPVEYOR_BUILD_FOLDER \
      bscdataclay/continuous-integration:reporting
notifications:
  - provider: Email
    to:
      - dgasull@bsc.es
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true